apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: ui-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - name: ui-container
        image: us-central1-docker.pkg.dev/konaai-dev-462909/q-test/api:Latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "70m"
          limits:
            memory: "128Mi"
            cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP 
